spring:
  application:
    name: webshop

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webshop
    username: postgres
    password: root
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: always
      platform: postgres

app:
 security:
  introspectURI: http://localhost:8090/oauth2/introspect
  resourceServerID: resourceserver
  resourceServerSecret: secret
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
logging:
 level:
  org:
   springframework:
    web: debug
    security: debug